// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrAj-nlWu_ownUz0ON7HJV52_ssDrwFOs',
    appId: '1:952835499596:web:5c44bdde12ffa69d9036e9',
    messagingSenderId: '952835499596',
    projectId: 'all-notes-6e9c7',
    authDomain: 'all-notes-6e9c7.firebaseapp.com',
    storageBucket: 'all-notes-6e9c7.appspot.com',
    measurementId: 'G-R44P5YEY6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnkJGELjmrynqkdw9KLNjCruQpuGSn7Fg',
    appId: '1:952835499596:android:b9eb64a0f0a435f89036e9',
    messagingSenderId: '952835499596',
    projectId: 'all-notes-6e9c7',
    storageBucket: 'all-notes-6e9c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCeFal5mxJ3nib7kcpS6ZuntjIiXfjuzs',
    appId: '1:952835499596:ios:6d638b900a33c78d9036e9',
    messagingSenderId: '952835499596',
    projectId: 'all-notes-6e9c7',
    storageBucket: 'all-notes-6e9c7.appspot.com',
    iosBundleId: 'com.example.allNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCeFal5mxJ3nib7kcpS6ZuntjIiXfjuzs',
    appId: '1:952835499596:ios:20fee1d18dc16b9d9036e9',
    messagingSenderId: '952835499596',
    projectId: 'all-notes-6e9c7',
    storageBucket: 'all-notes-6e9c7.appspot.com',
    iosBundleId: 'com.example.allNotes.RunnerTests',
  );
}
